### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by durner** [hschmidtchen/hschmidtchen.github.io#2]
Do we want to include the final scoreboard?

**Comment by hschmidtchen** [comment]
Sure, I would suggest to add it either in the solutions section or in the timeline for the race event.
Maybe even both...

**Comment by durner** [comment]
Alright I have the picture of the final results on my phone - I'll add it and do some medals for the three champions next to the team name in the teams section!

**Comment by durner** [comment]
added the times but needs some design rework :-)
