### ISSUE TITLE
Teams Section

### ISSUE THREAD

**Issue by durner** [hschmidtchen/hschmidtchen.github.io#3]
Ask for Github Repos and short summary of method, hopefully find a vid for each group and add the content.

**Comment by FroeMic** [comment]
I changed the position of the github icon in the team section and added the description and repo of  my team.

Could you please add the videos of all teams to the repo already?

**Comment by FroeMic** [comment]
I restructured the 'Solution' section so that the race time are now shown within the tabs (saves space) and added all the missing teams, so only the content has to be added.

**Comment by durner** [comment]
Nice rework! Like it alot! I'll do the rest soon - just hoping to get everybody's github repo + description!

**Comment by durner** [comment]
Added all the videos and students in 805c1370df0cc60e49cce80b147a4dcb47cc8f88 - just missing some github urls and description texts.

**Comment by FroeMic** [comment]
I cannot play the team videos on mobile (Safari, iOS 10). If you have time you can try to fix it. No top priority though.

**Comment by FroeMic** [comment]
I am missing to say 'thanks' more often 😄 Nicely done :)

**Comment by durner** [comment]
Okay - I got two codecs into it. One is webm which is not supported by the fruit at all and the other one is mp4. WebM works like a charm on all Windows & Linux (incl. Android) devices with recent Chrome and Firefox versions. As far as I know the MP4 vids should work on Safari, Chrome and Firefox with MacOS.

**Comment by durner** [comment]
> One important thing to note is that "iDevices" doesn't support all the varieties of mp4. Here is a small list about MPEG-4 and H.264 supported varieties. (https://github.com/aframevr/aframe/issues/1846)

I used the standard YoutubeHD-720 settings aka 720p with 25 fps for the mp4 vids. Maybe this might not work with the HTML5 video tags of iDevices. But honestly I don't know the problem, and I don't have any Apple devices here :apple:

**Comment by FroeMic** [comment]
Seems to be a problem with the configuration on my iPhone 5 only. I can't play the team videos in Safari / Chrome / Opera app. I double checked with my mom's iPhone 6 and iPad Air. Works fine with both of them. Sorry for the false alarm ;-)

**Comment by durner** [comment]
> Check for the least powerful device to run the video on (we target the iPhone 5S as the least powerful device on iOS). For idevices use 1366 x 683 h.264 5 mb/s. It runs smooth and looks very crisp.

It seems that 720p 25fps with 5Mb/s in h264 and mpeg3 @256kbit/s might be too much for the iphone 5.

**Comment by durner** [comment]
@FroeMic please recheck the yolonese video if you are able to play it. I added a iyolonese.mp4 as the third video for the html5 video tag.

**Comment by FroeMic** [comment]
still doesn't play. I wouldn't care too much for iDevices as old (>4 years) as the iPhone 5 though.

**Comment by durner** [comment]
That's why I don't like web programming stuff :no_entry_sign:

**Comment by FroeMic** [comment]
I wrote Victoria and Jakob about their team section to increase the 'pressure' ;-)

**Comment by magnusja** [comment]
I added Victorias and Jakobs stuff, are we finished then?
