### ISSUE TITLE
About Section

### ISSUE THREAD

**Issue by FroeMic** [hschmidtchen/hschmidtchen.github.io#6]
We need a short introduction what the Drone Elective is all about right at the beginning of the website. Best would be a short text and to embbed the youtube video Laurenz posted earlier (https://youtu.be/sfDL8KkP018).

**Comment by durner** [comment]
I can integrate the video, but textwise see #7

**Comment by FroeMic** [comment]
Let's go step by step. Could you add the Youtube video and maybe some lorem ipsum text for layouting?

**Comment by FroeMic** [comment]
I just did it :D Took just a few minutes :-) Now we just need meaningful content.

**Comment by durner** [comment]
Come on, you gave me less than an hour to respond haha :) All jokes aside, good work - I'll continue with #3!

**Comment by FroeMic** [comment]
Haha sry, I wrote it and was like 'actually delegating this is more work than doing it' 💃

**Comment by FroeMic** [comment]
Added text (strongly inspired by last year's website)
