### ISSUE TITLE
Timeline Descriptions

### ISSUE THREAD

**Issue by FroeMic** [hschmidtchen/hschmidtchen.github.io#7]
We need a short description of what we did on each of the days of the workshop to show that it was not 'just' a hackathon and provide more information about the content of the course.

**Comment by durner** [comment]
Do you know whether the PR / Social Team is in charge for that or are we supposed to write it?

**Comment by FroeMic** [comment]
I will quickly add some text tomorrow. We should still ask the PR/Social Team but if the do not respond in time we still have something.

**Comment by FroeMic** [comment]
Added some text (not quickly though). Time to get in touch with the PR team.

**Comment by FroeMic** [comment]
Removed some typos. I will close this issue now and wait for patrick's feedback.
