### ISSUE TITLE
Missing Lecturers

### ISSUE THREAD

**Issue by FroeMic** [hschmidtchen/hschmidtchen.github.io#9]
We are still missing the DHL workshop lecturers and the DHL team themselves. Additionally we should provide some information about the lecturers' (professional / academic) background.

**Comment by hschmidtchen** [comment]
I will write an email to Patrick and ask him about it.

**Comment by hschmidtchen** [comment]
Please do not mention the DHL Sponsorship since this involves heavy interference with the DHL Communication department.

Cheers,
Patrick

2016-09-05 23:04 GMT+02:00 Hagen Schmidtchen hagen.schmidtchen@googlemail.com:

```
Hey Patrick,

we would like to mention the DHL team and the DHL lecturers on the website but have not found any information about them in the course material.

Could you please provide us with their names(team and lecturers) and their professional/academic backgrounds(lecturers only)?

Thanks!

Hagen
```

**Comment by hschmidtchen** [comment]
Looks like we are supposed to leave it completely out...
Lets just call the last day race day and dont mention DHL in the workshop title.

**Comment by FroeMic** [comment]
Thanks, @hschmidtchen. I will remove all DHL references tomorrow.

**Comment by durner** [comment]
Haha - Okay, let's delete this issue as well :dizzy_face:

**Comment by FroeMic** [comment]
I removed all DHL references. The issue is still open though, since we should add the Felix and Felix to the Lecturers section. Additionally, it would be good to provide a short description to all lecturers :-)

**Comment by FroeMic** [comment]
Added them.
